version: "3.9"
services:
  web_service:
    build:
      context: .
      dockerfile: ./devops/backend/Dockerfile
    restart: unless-stopped
    env_file:
      - ./.env
    expose:
      - "8000"
    volumes:
      - static_volume:/app/backend/static
      - media_volume:/app/backend/media
    depends_on:
      - db
    deploy:
      mode: replicated
      replicas: 3


  db:
    image: postgres:16.2-alpine3.19
    env_file:
      - ./.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

  nginx:
    build:
      context: .
      dockerfile: ./devops/nginx/Dockerfile
    ports:
      - "80:80"
    volumes:
      - static_volume:/app/backend/static
      - media_volume:/app/backend/media

volumes:
  postgres_data:
  static_volume:
  media_volume: