version: "3.9"
services:
  web_service:
    build:
      context: .
      dockerfile: ./devops/backend/Dockerfile
    restart: unless-stopped
    entrypoint: /app/devops/backend/entrypoint.sh
    env_file:
      - ./.env
    expose:
      - "8000"
    volumes:
      - static_volume:/app/backend/staticfiles
      - media_volume:/app/backend/media
      - .:/app
    depends_on:
      - db
    deploy:
      mode: replicated
      replicas: 3


  db:
    image: postgres:16.2-alpine3.19
    env_file:
      - ./.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    expose:
      - "5432"
  nginx:
    build: ./devops/nginx/.
    ports:
      - "80:80"
    depends_on:
      - web_service
volumes:
  postgres_data:
  static_volume:
  media_volume:
